# Generated by Django 4.2 on 2023-04-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productreview_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, verbose_name='Discount percentage'),
        ),
    ]
