# Generated by Django 4.2 on 2023-04-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product/%Y/%m/%d', verbose_name='Image'),
        ),
    ]
