# Generated by Django 4.2 on 2023-04-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='design',
            field=models.CharField(default='modern', max_length=30, verbose_name='Design'),
            preserve_default=False,
        ),
    ]
