# Generated by Django 4.2 on 2023-04-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default='supplier@gmail.com', max_length=50, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
