# Generated by Django 4.2 on 2023-04-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saved',
        ),
    ]
