# Generated by Django 4.2 on 2023-04-19 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_table_shippingaddress_payment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='payment',
        ),
        migrations.AlterModelTable(
            name='shippingaddress',
            table='shipping',
        ),
    ]
