# Generated by Django 4.2 on 2023-04-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_image'),
        ('order', '0004_order_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CC', 'Credit Card'), ('DC', 'Debit Card'), ('PP', 'PayPal'), ('GP', 'Google Pay'), ('AP', 'Apple Pay'), ('BT', 'Bank Transfer'), ('COD', 'Cash on Delivery'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('CA', 'Cash')], default='', max_length=24),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
